### ISSUE TITLE
News Feed

### ISSUE THREAD

**Issue by JacquelineMorck** [UnionDesign/keyin#9]
Awesome to have this -

Can we please call it Blog not news

Can we have a side bar on right where you can filter by industry - I will probably add a link to each industry page with the results filtered already for the industry.

there will be global entries, stuff about keyin, industry entries, and news stuff

Is it hard to add in an rss feed of twitter???

having tags on topics would also be very nice.

**Comment by UnionDesign** [comment]
Changed "News" to "Blog"

**Comment by UnionDesign** [comment]
I did create categories so you can create them at will. For consistency I put them in a secondary navigation style (dark grey horizontal strip below highlighted tab) like Industries and Child pages.

Could we say this will suffice for launch (spent a few hours on it already) and if we want tags, twitter, hierarchical categories and a sidebar instead of my secondary nav style... we can do that as a part of a post-launch mini-project? Along with the gallery tweaks we talked about?

**Comment by JacquelineMorck** [comment]
yes this works!
